apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-laravel-app.fullname" . }}
  labels:
    {{- include "my-laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  selector:
    {{- include "my-laravel-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}
