apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    {{- include "my-laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  selector:
    {{- include "my-laravel-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  type: ClusterIP
