apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  labels:
    {{- include "my-laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}
  storageClassName: {{ .Values.database.storageClass }}
