apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-laravel-app.fullname" . }}-secret
  labels:
    {{- include "my-laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
type: Opaque
stringData:
  APP_KEY: {{ .Values.app.key | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}
