apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app

resources:
- secret.yaml
- configmap.yaml
- pvc.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- backup-cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: kubequest
