apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: kubequest
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
  DB_PASSWORD: "app_password"
  DB_ROOT_PASSWORD: "app_root_password"
