apiVersion: v2
name: my-laravel-app
description: Application Laravel avec MySQL - KubeQuest
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - laravel
  - php
  - mysql
maintainers:
  - name: groupe-39
